### ISSUE TITLE
I can't install Cam-Hackers

### ISSUE THREAD

**Issue by andryx06** [AngelSecurityTeam/Cam-Hackers#3]
I can download the folder through the terminal.
I follow all the steps shown by the developer of the tool
but when i try to start "cam-hacker.py" it gives me the following error:

Traceback (most recent call last):
   File "cam-hackers.py", line 3, in <module>
     eval (compile (base64.b64decode (cam), '', 'exec'))
   File "", line 8, in <module>
   File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'requests'.

I remember I have python3 and git, but still it doesn't make me start cam-hackers.py

please someone help me
thank you.
![Schermata 2020-03-05 06:17:25](https://user-images.githubusercontent.com/61657149/75976878-3df26080-5ea9-11ea-8542-79d0d1724f9b.png)

**Comment by WOLFIE-OG** [comment]
pip3 install requests

**Comment by SharkAttack420** [comment]
It will not show me ip address
