### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by Kimani3050** [AngelSecurityTeam/Cam-Hackers#35]
I want to delete the directory but i have no permission. How do i go about it?

**Comment by Anonymous101404** [comment]
> I want to delete the directory but i have no permission. How do i go about it?

"sudo" or "sudo su"

**Comment by Harsh793XD** [comment]
I don't have permission to open the "Cam-Hackers"
Its showing "bash: cd: Cam-Hackers: Permission denied"
