### ISSUE TITLE
nothing happened

### ISSUE THREAD

**Issue by pretech86** [AngelSecurityTeam/Cam-Hackers#7]
i run the tool but nothing happened

**Comment by Bohemia91** [comment]
X2

**Comment by keenswong** [comment]
yes, nothing happened

**Comment by nitin724** [comment]
nothing happened

**Comment by Zaarc** [comment]
thats because the tool is fake!

**Comment by darkhacknet** [comment]
> thats because the tool is fake!

the tool is real, I used it about 1 year ago ! but not seems to be disabled or something !
