### ISSUE TITLE
login

### ISSUE THREAD

**Issue by vipulyada** [AngelSecurityTeam/Cam-Hackers#8]
i runned this tool
but after i use that IP address to open that cam
it tells me to login

**Comment by lasagnaaf** [comment]
u need a password for camera login. no1 can help, u can guess passwords

**Comment by RedGurdian** [comment]
you dont need a password to sign in, i know it sounds crazy but you dont because i pressed ctrl + U
and i looked at the password value and it had opened and closed string so its litter-lay nothing.

**Comment by drissouakass** [comment]
Hey

**Comment by drissouakass** [comment]
Do you know any think about programer

**Comment by drissouakass** [comment]
Iam not
