### ISSUE TITLE
How to solve 

### ISSUE THREAD

**Issue by BLACKJHON1** [AngelSecurityTeam/Cam-Hackers#97]
![Screenshot_2023-11-25-20-02-58-385_com termux](https://github.com/AngelSecurityTeam/Cam-Hackers/assets/106651353/3a13d93a-ed9f-4697-84fd-3afb30cc33af)

File "/data/data/com.termux/files/home/camera/Cam-Hackers/cam-hackers.py", line 6, in <module>
    import requests, re , colorama ,random
ModuleNotFoundError: No module named 'requests'

**Comment by Looking4Crack** [comment]
You ever figure this out?
